# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84dcda4ad439e9249703d58d2f399748bd88ac623bc2e543ba727bbec91034162502109dea6d07ddac89c4bb21950b05f433328dea60b53e3f19a103810d78f0
  GMAIL_USERNAME: <%= ENV["GMAIL_USERNAME"] %>
  GMAIL_PASSWORD: <%= ENV["GMAIL_PASSWORD"] %>

test:
  secret_key_base: 64d0195b6a67569a9c23be168ddefbfe92798e2a11a78b00388c00a70daf261d55e253f6651ad0c76770c5ff7e7bab4d9e09a0cbeb8fa1c73a09ed83b8bbda40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

    #put back

